#!/bin/bash
# Generate firmware/esp32-wroom-mockingbird/src/secrets.h from
# ~/repos/.scratch/mockingbird-wifi.txt — never hand-edit secrets.h.
set -euo pipefail
SCRATCH=~/repos/.scratch
DEST=~/repos/mockingbird/firmware/esp32-wroom-mockingbird/src/secrets.h

[ -f "$SCRATCH/mockingbird-wifi.txt" ] || { echo "missing $SCRATCH/mockingbird-wifi.txt" >&2; exit 1; }
SSID=$(grep ^SSID= "$SCRATCH/mockingbird-wifi.txt" | cut -d= -f2-)
PSK=$(grep ^PSK= "$SCRATCH/mockingbird-wifi.txt" | cut -d= -f2-)

cat > "$DEST" <<EOF
// AUTO-GENERATED by scripts/gen-esp32-secrets.sh — do not edit.
#pragma once
#define MOCKINGBIRD_WIFI_SSID "$SSID"
#define MOCKINGBIRD_WIFI_PSK  "$PSK"
EOF
chmod 600 "$DEST"
echo "wrote $DEST"
